apiVersion: v1
kind: Template
metadata:
  name: summit-lab-spring-trades-db
parameters:
  - name: DATABASE_NAME
    value: trades
    description: The name of the database to use
    required: true
  - name: DATABASE_USERNAME
    generate: expression
    from: "[a-zA-Z]{32}"
    description: The database username
  - name: DATABASE_PASSWORD
    generate: expression
    from: "[a-zA-Z0-9]{32}"
    description: The database password
  - name: DATABASE_ADMIN_PASSWORD
    generate: expression
    from: "[a-zA-Z0-9]{32}"
    description: The database admin password
objects:
  - kind: Secret
    apiVersion: v1
    metadata:
      name: summit-lab-spring-trades-db
      labels:
        application: summit-lab-spring-trades
      annotations:
        template.openshift.io/expose-database_name: '{.data[''database-name'']}'
        template.openshift.io/expose-password: '{.data[''database-password'']}'
        template.openshift.io/expose-username: '{.data[''database-user'']}'
        template.openshift.io/expose-admin_password: '{.data["database-admin-password"]}'
    stringData:
      database-name: ${DATABASE_NAME}
      database-password: ${DATABASE_PASSWORD}
      database-user: ${DATABASE_USERNAME}
      database-admin-password: ${DATABASE_ADMIN_PASSWORD}
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: summit-lab-spring-trades-db
      labels:
        template: postgresql-ephemeral-template
        application: summit-lab-spring-trades
      annotations:
        template.alpha.openshift.io/wait-for-ready: "true"
    spec:
      replicas: 1
      strategy:
        type: Recreate
      selector:
        name: summit-lab-spring-trades-db
      template:
        metadata:
          name: summit-lab-spring-trades-db
          labels:
            name: summit-lab-spring-trades-db
        spec:
          containers:
            - env:
                - name: POSTGRESQL_USER
                  valueFrom:
                    secretKeyRef:
                      name: summit-lab-spring-trades-db
                      key: database-user
                - name: POSTGRESQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: summit-lab-spring-trades-db
                      key: database-password
                - name: POSTGRESQL_DATABASE
                  valueFrom:
                    secretKeyRef:
                      name: summit-lab-spring-trades-db
                      key: database-name
                - name: POSTGRESQL_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: summit-lab-spring-trades-db
                      key: database-admin-password
              name: summit-lab-spring-trades-db
              image: rhscl/postgresql-96-rhel7
              imagePullPolicy: IfNotPresent
              ports:
                - containerPort: 5432
                  protocol: TCP
              livenessProbe:
                failureThreshold: 3
                initialDelaySeconds: 30
                periodSeconds: 10
                successThreshold: 1
                exec:
                  command:
                    - /bin/sh
                    - -i
                    - -c
                    - pg_isready -h 127.0.0.1 -p 5432
                timeoutSeconds: 1
              readinessProbe:
                exec:
                  command:
                    - /bin/sh
                    - -i
                    - -c
                    - psql -h 127.0.0.1 -U $POSTGRESQL_USER -q -d $POSTGRESQL_DATABASE -c 'SELECT 1'
                failureThreshold: 3
                initialDelaySeconds: 5
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
              resources:
                limits:
                  memory: 512Mi
              securityContext:
                privileged: false
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - summit-lab-spring-trades-db
            from:
              kind: ImageStreamTag
              name: postgresql:9.6
              namespace: openshift
      volumes:
        - name: summit-lab-spring-trades-db-data
          emptyDir: {}
  - kind: Service
    apiVersion: v1
    metadata:
      name: summit-lab-spring-trades-db
      labels:
        template: postgresql-ephemeral-template
        application: summit-lab-spring-trades
    spec:
      ports:
        - name: postgres
          port: 5432
          protocol: TCP
          targetPort: 5432
      selector:
        name: summit-lab-spring-trades-db
